version: 2

project_name: videohub_exporter

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      # Populate fields at build time for the prometheus version collector
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "registry.gitlab.com/patopest/videohub-exporter:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "registry.gitlab.com/patopest/videohub-exporter:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

# Combine manifests to create one multi-platform image
docker_manifests:
  - name_template: "registry.gitlab.com/patopest/videohub-exporter:{{ .Tag }}"
    image_templates:
      - "registry.gitlab.com/patopest/videohub-exporter:{{ .Tag }}-amd64"
      - "registry.gitlab.com/patopest/videohub-exporter:{{ .Tag }}-arm64"
  - name_template: "registry.gitlab.com/patopest/videohub-exporter:latest"
    image_templates:
      - "registry.gitlab.com/patopest/videohub-exporter:{{ .Tag }}-amd64"
      - "registry.gitlab.com/patopest/videohub-exporter:{{ .Tag }}-arm64"

release:
  # Add github manually
  github:
    owner: patopesto
    name: videohub-exporter
